---

- hosts: all
  become: true
  tasks:

  - name: install kubelet and docker
    package:
      name:
        - "{{ kubelet }}"
        - "{{ docker }}" #this_are_variable_that_set_in_invetntory
      state: latest
      update_cache: yes
