---

- hosts: all
  become: true
  tasks:

  - name: install kubelet
    apt:
      name:
        - kubelet
        - docker
      state: latest
      update_cache: yes
    when:  ansible_distribution in ["Debian", "Ubuntu"]

  - name: install kubelet
    dnf:
      name:
        - kubelet
        - docker
      state: latest
      update_cache: yes
    when:  ansible_distribution in ["CentOS", "Fedora"]
