---

- hosts: all
  become: true
  tasks:

  - name: copy important file
    copy:
      src: test_copy.yaml 
      dest: /var/lib/chert.yaml
      owner: root
      group: root
      mode: 0644


  - name: install kubelet and docker
    package:
      name:
        - "{{ kubelet }}"
        - "{{ docker }}" #this_are_variable_that_set_in_invetntory
      state: latest
      update_cache: yes
